# Generated by Django 5.0.1 on 2024-03-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Faculty', 'Faculty')], max_length=10),
        ),
    ]
