# Generated by Django 5.0.1 on 2024-03-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
