# Generated by Django 5.0.1 on 2024-03-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0003_rename_user_user1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user1',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
