# Generated by Django 5.0.1 on 2024-03-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0005_myuser_alter_application_name_delete_user1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
