# Generated by Django 5.0.1 on 2024-03-13 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0007_alter_myuser_options_myuser_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('university', models.CharField(max_length=70)),
                ('program', models.CharField(max_length=70)),
                ('study_mode', models.CharField(choices=[('Offline', 'Offline')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
