# Generated by Django 5.0.1 on 2024-03-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0008_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
